/*
 * generated by Xtext
 */
package uw.cs.watform.forml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FormlRuntimeModule extends uw.cs.watform.forml.AbstractFormlRuntimeModule {

}
