/*
 * generated by Xtext
 */
package uw.cs.watform.forml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uw.cs.watform.forml.services.FormlGrammarAccess;

public class FormlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FormlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected uw.cs.watform.forml.parser.antlr.internal.InternalFormlParser createParser(XtextTokenStream stream) {
		return new uw.cs.watform.forml.parser.antlr.internal.InternalFormlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}
	
	public FormlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FormlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
