/*
 * generated by Xtext
 */
package uw.cs.watform.forml.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractFormlValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(uw.cs.watform.forml.forml.FormlPackage.eINSTANCE);
		return result;
	}
}
