/*
 * generated by Xtext
 */
package uw.cs.watform.forml.ui;

import javax.annotation.Generated;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.codetemplates.ui.partialEditing.PartialEditingContentAssistContextFactory;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FormlUiModule extends uw.cs.watform.forml.ui.AbstractFormlUiModule {
	public FormlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	
//	@java.lang.Override
//	public java.lang.Class<? extends org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext.Factory> bindContentAssistContext$Factory() {
//		return PartialEditingContentAssistContextFactory.class;
//	};

}
