/**
 */
package uw.cs.watform.forml.forml.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import uw.cs.watform.forml.forml.util.FormlAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FormlItemProviderAdapterFactory extends FormlAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FormlItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.System} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemItemProvider systemItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.System}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemAdapter() {
		if (systemItemProvider == null) {
			systemItemProvider = new SystemItemProvider(this);
		}

		return systemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.WorldModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorldModelItemProvider worldModelItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.WorldModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorldModelAdapter() {
		if (worldModelItemProvider == null) {
			worldModelItemProvider = new WorldModelItemProvider(this);
		}

		return worldModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Constraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstraintItemProvider constraintItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Constraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstraintAdapter() {
		if (constraintItemProvider == null) {
			constraintItemProvider = new ConstraintItemProvider(this);
		}

		return constraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.ExprRef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExprRefItemProvider exprRefItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.ExprRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExprRefAdapter() {
		if (exprRefItemProvider == null) {
			exprRefItemProvider = new ExprRefItemProvider(this);
		}

		return exprRefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Concept} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConceptItemProvider conceptItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Concept}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConceptAdapter() {
		if (conceptItemProvider == null) {
			conceptItemProvider = new ConceptItemProvider(this);
		}

		return conceptItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Roleable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleableItemProvider roleableItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Roleable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleableAdapter() {
		if (roleableItemProvider == null) {
			roleableItemProvider = new RoleableItemProvider(this);
		}

		return roleableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Relationship} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationshipItemProvider relationshipItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Relationship}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationshipAdapter() {
		if (relationshipItemProvider == null) {
			relationshipItemProvider = new RelationshipItemProvider(this);
		}

		return relationshipItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.AttributeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeTypeItemProvider attributeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.AttributeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeTypeAdapter() {
		if (attributeTypeItemProvider == null) {
			attributeTypeItemProvider = new AttributeTypeItemProvider(this);
		}

		return attributeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.StringType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringTypeItemProvider stringTypeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.StringType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringTypeAdapter() {
		if (stringTypeItemProvider == null) {
			stringTypeItemProvider = new StringTypeItemProvider(this);
		}

		return stringTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.IntType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntTypeItemProvider intTypeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.IntType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntTypeAdapter() {
		if (intTypeItemProvider == null) {
			intTypeItemProvider = new IntTypeItemProvider(this);
		}

		return intTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.BoolType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BoolTypeItemProvider boolTypeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.BoolType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBoolTypeAdapter() {
		if (boolTypeItemProvider == null) {
			boolTypeItemProvider = new BoolTypeItemProvider(this);
		}

		return boolTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.ReferenceType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceTypeItemProvider referenceTypeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.ReferenceType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceTypeAdapter() {
		if (referenceTypeItemProvider == null) {
			referenceTypeItemProvider = new ReferenceTypeItemProvider(this);
		}

		return referenceTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Multiplicity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiplicityItemProvider multiplicityItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Multiplicity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiplicityAdapter() {
		if (multiplicityItemProvider == null) {
			multiplicityItemProvider = new MultiplicityItemProvider(this);
		}

		return multiplicityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Cardinality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CardinalityItemProvider cardinalityItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Cardinality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCardinalityAdapter() {
		if (cardinalityItemProvider == null) {
			cardinalityItemProvider = new CardinalityItemProvider(this);
		}

		return cardinalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Role} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleItemProvider roleItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Role}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleAdapter() {
		if (roleItemProvider == null) {
			roleItemProvider = new RoleItemProvider(this);
		}

		return roleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Decl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeclItemProvider declItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Decl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeclAdapter() {
		if (declItemProvider == null) {
			declItemProvider = new DeclItemProvider(this);
		}

		return declItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Message} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageItemProvider messageItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Message}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMessageAdapter() {
		if (messageItemProvider == null) {
			messageItemProvider = new MessageItemProvider(this);
		}

		return messageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.InputList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputListItemProvider inputListItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.InputList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputListAdapter() {
		if (inputListItemProvider == null) {
			inputListItemProvider = new InputListItemProvider(this);
		}

		return inputListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.OutputList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputListItemProvider outputListItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.OutputList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputListAdapter() {
		if (outputListItemProvider == null) {
			outputListItemProvider = new OutputListItemProvider(this);
		}

		return outputListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.RefMessage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RefMessageItemProvider refMessageItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.RefMessage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRefMessageAdapter() {
		if (refMessageItemProvider == null) {
			refMessageItemProvider = new RefMessageItemProvider(this);
		}

		return refMessageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Node} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeItemProvider nodeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Node}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeAdapter() {
		if (nodeItemProvider == null) {
			nodeItemProvider = new NodeItemProvider(this);
		}

		return nodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.BehaviourModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BehaviourModelItemProvider behaviourModelItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.BehaviourModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBehaviourModelAdapter() {
		if (behaviourModelItemProvider == null) {
			behaviourModelItemProvider = new BehaviourModelItemProvider(this);
		}

		return behaviourModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.FeatureModule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureModuleItemProvider featureModuleItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.FeatureModule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureModuleAdapter() {
		if (featureModuleItemProvider == null) {
			featureModuleItemProvider = new FeatureModuleItemProvider(this);
		}

		return featureModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.StateMachine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateMachineItemProvider stateMachineItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.StateMachine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateMachineAdapter() {
		if (stateMachineItemProvider == null) {
			stateMachineItemProvider = new StateMachineItemProvider(this);
		}

		return stateMachineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.InitState} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InitStateItemProvider initStateItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.InitState}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInitStateAdapter() {
		if (initStateItemProvider == null) {
			initStateItemProvider = new InitStateItemProvider(this);
		}

		return initStateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Component} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentItemProvider componentItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Component}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentAdapter() {
		if (componentItemProvider == null) {
			componentItemProvider = new ComponentItemProvider(this);
		}

		return componentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Transition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionItemProvider transitionItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Transition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionAdapter() {
		if (transitionItemProvider == null) {
			transitionItemProvider = new TransitionItemProvider(this);
		}

		return transitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Priority} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PriorityItemProvider priorityItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Priority}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPriorityAdapter() {
		if (priorityItemProvider == null) {
			priorityItemProvider = new PriorityItemProvider(this);
		}

		return priorityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.TransList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransListItemProvider transListItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.TransList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransListAdapter() {
		if (transListItemProvider == null) {
			transListItemProvider = new TransListItemProvider(this);
		}

		return transListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Guard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GuardItemProvider guardItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Guard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGuardAdapter() {
		if (guardItemProvider == null) {
			guardItemProvider = new GuardItemProvider(this);
		}

		return guardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Trigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriggerItemProvider triggerItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Trigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriggerAdapter() {
		if (triggerItemProvider == null) {
			triggerItemProvider = new TriggerItemProvider(this);
		}

		return triggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Override} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OverrideItemProvider overrideItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Override}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOverrideAdapter() {
		if (overrideItemProvider == null) {
			overrideItemProvider = new OverrideItemProvider(this);
		}

		return overrideItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.WCE} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WCEItemProvider wceItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.WCE}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWCEAdapter() {
		if (wceItemProvider == null) {
			wceItemProvider = new WCEItemProvider(this);
		}

		return wceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.WCAList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WCAListItemProvider wcaListItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.WCAList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWCAListAdapter() {
		if (wcaListItemProvider == null) {
			wcaListItemProvider = new WCAListItemProvider(this);
		}

		return wcaListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.WCA} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WCAItemProvider wcaItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.WCA}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWCAAdapter() {
		if (wcaItemProvider == null) {
			wcaItemProvider = new WCAItemProvider(this);
		}

		return wcaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Action} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionItemProvider actionItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Action}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionAdapter() {
		if (actionItemProvider == null) {
			actionItemProvider = new ActionItemProvider(this);
		}

		return actionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.AssignList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssignListItemProvider assignListItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.AssignList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssignListAdapter() {
		if (assignListItemProvider == null) {
			assignListItemProvider = new AssignListItemProvider(this);
		}

		return assignListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Assign} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssignItemProvider assignItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Assign}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssignAdapter() {
		if (assignItemProvider == null) {
			assignItemProvider = new AssignItemProvider(this);
		}

		return assignItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Macro} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MacroItemProvider macroItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Macro}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMacroAdapter() {
		if (macroItemProvider == null) {
			macroItemProvider = new MacroItemProvider(this);
		}

		return macroItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Predicate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PredicateItemProvider predicateItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Predicate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPredicateAdapter() {
		if (predicateItemProvider == null) {
			predicateItemProvider = new PredicateItemProvider(this);
		}

		return predicateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.notPred} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected notPredItemProvider notPredItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.notPred}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createnotPredAdapter() {
		if (notPredItemProvider == null) {
			notPredItemProvider = new notPredItemProvider(this);
		}

		return notPredItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.andPred} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected andPredItemProvider andPredItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.andPred}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createandPredAdapter() {
		if (andPredItemProvider == null) {
			andPredItemProvider = new andPredItemProvider(this);
		}

		return andPredItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.impPred} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected impPredItemProvider impPredItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.impPred}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createimpPredAdapter() {
		if (impPredItemProvider == null) {
			impPredItemProvider = new impPredItemProvider(this);
		}

		return impPredItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.orPred} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected orPredItemProvider orPredItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.orPred}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createorPredAdapter() {
		if (orPredItemProvider == null) {
			orPredItemProvider = new orPredItemProvider(this);
		}

		return orPredItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.basePred} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected basePredItemProvider basePredItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.basePred}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createbasePredAdapter() {
		if (basePredItemProvider == null) {
			basePredItemProvider = new basePredItemProvider(this);
		}

		return basePredItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.boolExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected boolExprItemProvider boolExprItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.boolExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createboolExprAdapter() {
		if (boolExprItemProvider == null) {
			boolExprItemProvider = new boolExprItemProvider(this);
		}

		return boolExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.predExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected predExprItemProvider predExprItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.predExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createpredExprAdapter() {
		if (predExprItemProvider == null) {
			predExprItemProvider = new predExprItemProvider(this);
		}

		return predExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.predExpr2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected predExpr2ItemProvider predExpr2ItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.predExpr2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createpredExpr2Adapter() {
		if (predExpr2ItemProvider == null) {
			predExpr2ItemProvider = new predExpr2ItemProvider(this);
		}

		return predExpr2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.predExpr3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected predExpr3ItemProvider predExpr3ItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.predExpr3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createpredExpr3Adapter() {
		if (predExpr3ItemProvider == null) {
			predExpr3ItemProvider = new predExpr3ItemProvider(this);
		}

		return predExpr3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.setExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected setExprItemProvider setExprItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.setExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createsetExprAdapter() {
		if (setExprItemProvider == null) {
			setExprItemProvider = new setExprItemProvider(this);
		}

		return setExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.setExpr2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected setExpr2ItemProvider setExpr2ItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.setExpr2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createsetExpr2Adapter() {
		if (setExpr2ItemProvider == null) {
			setExpr2ItemProvider = new setExpr2ItemProvider(this);
		}

		return setExpr2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.setExpr3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected setExpr3ItemProvider setExpr3ItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.setExpr3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createsetExpr3Adapter() {
		if (setExpr3ItemProvider == null) {
			setExpr3ItemProvider = new setExpr3ItemProvider(this);
		}

		return setExpr3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.setExprBase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected setExprBaseItemProvider setExprBaseItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.setExprBase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createsetExprBaseAdapter() {
		if (setExprBaseItemProvider == null) {
			setExprBaseItemProvider = new setExprBaseItemProvider(this);
		}

		return setExprBaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.intExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected intExprItemProvider intExprItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.intExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createintExprAdapter() {
		if (intExprItemProvider == null) {
			intExprItemProvider = new intExprItemProvider(this);
		}

		return intExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.multExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected multExprItemProvider multExprItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.multExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createmultExprAdapter() {
		if (multExprItemProvider == null) {
			multExprItemProvider = new multExprItemProvider(this);
		}

		return multExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.intBase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected intBaseItemProvider intBaseItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.intBase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createintBaseAdapter() {
		if (intBaseItemProvider == null) {
			intBaseItemProvider = new intBaseItemProvider(this);
		}

		return intBaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.atomic} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected atomicItemProvider atomicItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.atomic}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createatomicAdapter() {
		if (atomicItemProvider == null) {
			atomicItemProvider = new atomicItemProvider(this);
		}

		return atomicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.unspecified} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected unspecifiedItemProvider unspecifiedItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.unspecified}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createunspecifiedAdapter() {
		if (unspecifiedItemProvider == null) {
			unspecifiedItemProvider = new unspecifiedItemProvider(this);
		}

		return unspecifiedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Fragment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FragmentItemProvider fragmentItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Fragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFragmentAdapter() {
		if (fragmentItemProvider == null) {
			fragmentItemProvider = new FragmentItemProvider(this);
		}

		return fragmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.FragmentType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FragmentTypeItemProvider fragmentTypeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.FragmentType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFragmentTypeAdapter() {
		if (fragmentTypeItemProvider == null) {
			fragmentTypeItemProvider = new FragmentTypeItemProvider(this);
		}

		return fragmentTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.StateContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateContextItemProvider stateContextItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.StateContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateContextAdapter() {
		if (stateContextItemProvider == null) {
			stateContextItemProvider = new StateContextItemProvider(this);
		}

		return stateContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.RegionContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegionContextItemProvider regionContextItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.RegionContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRegionContextAdapter() {
		if (regionContextItemProvider == null) {
			regionContextItemProvider = new RegionContextItemProvider(this);
		}

		return regionContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.StateMachineContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateMachineContextItemProvider stateMachineContextItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.StateMachineContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateMachineContextAdapter() {
		if (stateMachineContextItemProvider == null) {
			stateMachineContextItemProvider = new StateMachineContextItemProvider(this);
		}

		return stateMachineContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.TranFragment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TranFragmentItemProvider tranFragmentItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.TranFragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTranFragmentAdapter() {
		if (tranFragmentItemProvider == null) {
			tranFragmentItemProvider = new TranFragmentItemProvider(this);
		}

		return tranFragmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.WCAFragmentList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WCAFragmentListItemProvider wcaFragmentListItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.WCAFragmentList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWCAFragmentListAdapter() {
		if (wcaFragmentListItemProvider == null) {
			wcaFragmentListItemProvider = new WCAFragmentListItemProvider(this);
		}

		return wcaFragmentListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.WCAFragment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WCAFragmentItemProvider wcaFragmentItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.WCAFragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWCAFragmentAdapter() {
		if (wcaFragmentItemProvider == null) {
			wcaFragmentItemProvider = new WCAFragmentItemProvider(this);
		}

		return wcaFragmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Entity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityItemProvider entityItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Entity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAdapter() {
		if (entityItemProvider == null) {
			entityItemProvider = new EntityItemProvider(this);
		}

		return entityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Association} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssociationItemProvider associationItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Association}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssociationAdapter() {
		if (associationItemProvider == null) {
			associationItemProvider = new AssociationItemProvider(this);
		}

		return associationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Attribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeItemProvider attributeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Attribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeAdapter() {
		if (attributeItemProvider == null) {
			attributeItemProvider = new AttributeItemProvider(this);
		}

		return attributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Function} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionItemProvider functionItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Function}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAdapter() {
		if (functionItemProvider == null) {
			functionItemProvider = new FunctionItemProvider(this);
		}

		return functionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.UndefinedType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UndefinedTypeItemProvider undefinedTypeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.UndefinedType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUndefinedTypeAdapter() {
		if (undefinedTypeItemProvider == null) {
			undefinedTypeItemProvider = new UndefinedTypeItemProvider(this);
		}

		return undefinedTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Aggregation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AggregationItemProvider aggregationItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Aggregation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAggregationAdapter() {
		if (aggregationItemProvider == null) {
			aggregationItemProvider = new AggregationItemProvider(this);
		}

		return aggregationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Composition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositionItemProvider compositionItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Composition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositionAdapter() {
		if (compositionItemProvider == null) {
			compositionItemProvider = new CompositionItemProvider(this);
		}

		return compositionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.CompDecl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompDeclItemProvider compDeclItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.CompDecl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompDeclAdapter() {
		if (compDeclItemProvider == null) {
			compDeclItemProvider = new CompDeclItemProvider(this);
		}

		return compDeclItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Input} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputItemProvider inputItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Input}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputAdapter() {
		if (inputItemProvider == null) {
			inputItemProvider = new InputItemProvider(this);
		}

		return inputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Output} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputItemProvider outputItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Output}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputAdapter() {
		if (outputItemProvider == null) {
			outputItemProvider = new OutputItemProvider(this);
		}

		return outputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Feature} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureItemProvider featureItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Feature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureAdapter() {
		if (featureItemProvider == null) {
			featureItemProvider = new FeatureItemProvider(this);
		}

		return featureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.SPL} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SPLItemProvider splItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.SPL}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSPLAdapter() {
		if (splItemProvider == null) {
			splItemProvider = new SPLItemProvider(this);
		}

		return splItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.XORNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XORNodeItemProvider xorNodeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.XORNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXORNodeAdapter() {
		if (xorNodeItemProvider == null) {
			xorNodeItemProvider = new XORNodeItemProvider(this);
		}

		return xorNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.AndNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AndNodeItemProvider andNodeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.AndNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAndNodeAdapter() {
		if (andNodeItemProvider == null) {
			andNodeItemProvider = new AndNodeItemProvider(this);
		}

		return andNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.OrNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrNodeItemProvider orNodeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.OrNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrNodeAdapter() {
		if (orNodeItemProvider == null) {
			orNodeItemProvider = new OrNodeItemProvider(this);
		}

		return orNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.FeatureNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureNodeItemProvider featureNodeItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.FeatureNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureNodeAdapter() {
		if (featureNodeItemProvider == null) {
			featureNodeItemProvider = new FeatureNodeItemProvider(this);
		}

		return featureNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Enumeration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationItemProvider enumerationItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Enumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationAdapter() {
		if (enumerationItemProvider == null) {
			enumerationItemProvider = new EnumerationItemProvider(this);
		}

		return enumerationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.EnumConst} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumConstItemProvider enumConstItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.EnumConst}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumConstAdapter() {
		if (enumConstItemProvider == null) {
			enumConstItemProvider = new EnumConstItemProvider(this);
		}

		return enumConstItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.State} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateItemProvider stateItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.State}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateAdapter() {
		if (stateItemProvider == null) {
			stateItemProvider = new StateItemProvider(this);
		}

		return stateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Region} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegionItemProvider regionItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Region}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRegionAdapter() {
		if (regionItemProvider == null) {
			regionItemProvider = new RegionItemProvider(this);
		}

		return regionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link uw.cs.watform.forml.forml.Variable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableItemProvider variableItemProvider;

	/**
	 * This creates an adapter for a {@link uw.cs.watform.forml.forml.Variable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableAdapter() {
		if (variableItemProvider == null) {
			variableItemProvider = new VariableItemProvider(this);
		}

		return variableItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (systemItemProvider != null) systemItemProvider.dispose();
		if (worldModelItemProvider != null) worldModelItemProvider.dispose();
		if (constraintItemProvider != null) constraintItemProvider.dispose();
		if (exprRefItemProvider != null) exprRefItemProvider.dispose();
		if (conceptItemProvider != null) conceptItemProvider.dispose();
		if (roleableItemProvider != null) roleableItemProvider.dispose();
		if (relationshipItemProvider != null) relationshipItemProvider.dispose();
		if (attributeTypeItemProvider != null) attributeTypeItemProvider.dispose();
		if (stringTypeItemProvider != null) stringTypeItemProvider.dispose();
		if (intTypeItemProvider != null) intTypeItemProvider.dispose();
		if (boolTypeItemProvider != null) boolTypeItemProvider.dispose();
		if (referenceTypeItemProvider != null) referenceTypeItemProvider.dispose();
		if (multiplicityItemProvider != null) multiplicityItemProvider.dispose();
		if (cardinalityItemProvider != null) cardinalityItemProvider.dispose();
		if (roleItemProvider != null) roleItemProvider.dispose();
		if (declItemProvider != null) declItemProvider.dispose();
		if (messageItemProvider != null) messageItemProvider.dispose();
		if (inputListItemProvider != null) inputListItemProvider.dispose();
		if (outputListItemProvider != null) outputListItemProvider.dispose();
		if (refMessageItemProvider != null) refMessageItemProvider.dispose();
		if (nodeItemProvider != null) nodeItemProvider.dispose();
		if (behaviourModelItemProvider != null) behaviourModelItemProvider.dispose();
		if (featureModuleItemProvider != null) featureModuleItemProvider.dispose();
		if (stateMachineItemProvider != null) stateMachineItemProvider.dispose();
		if (initStateItemProvider != null) initStateItemProvider.dispose();
		if (componentItemProvider != null) componentItemProvider.dispose();
		if (transitionItemProvider != null) transitionItemProvider.dispose();
		if (priorityItemProvider != null) priorityItemProvider.dispose();
		if (transListItemProvider != null) transListItemProvider.dispose();
		if (guardItemProvider != null) guardItemProvider.dispose();
		if (triggerItemProvider != null) triggerItemProvider.dispose();
		if (overrideItemProvider != null) overrideItemProvider.dispose();
		if (wceItemProvider != null) wceItemProvider.dispose();
		if (wcaListItemProvider != null) wcaListItemProvider.dispose();
		if (wcaItemProvider != null) wcaItemProvider.dispose();
		if (actionItemProvider != null) actionItemProvider.dispose();
		if (assignListItemProvider != null) assignListItemProvider.dispose();
		if (assignItemProvider != null) assignItemProvider.dispose();
		if (macroItemProvider != null) macroItemProvider.dispose();
		if (predicateItemProvider != null) predicateItemProvider.dispose();
		if (notPredItemProvider != null) notPredItemProvider.dispose();
		if (andPredItemProvider != null) andPredItemProvider.dispose();
		if (impPredItemProvider != null) impPredItemProvider.dispose();
		if (orPredItemProvider != null) orPredItemProvider.dispose();
		if (basePredItemProvider != null) basePredItemProvider.dispose();
		if (boolExprItemProvider != null) boolExprItemProvider.dispose();
		if (predExprItemProvider != null) predExprItemProvider.dispose();
		if (predExpr2ItemProvider != null) predExpr2ItemProvider.dispose();
		if (predExpr3ItemProvider != null) predExpr3ItemProvider.dispose();
		if (setExprItemProvider != null) setExprItemProvider.dispose();
		if (setExpr2ItemProvider != null) setExpr2ItemProvider.dispose();
		if (setExpr3ItemProvider != null) setExpr3ItemProvider.dispose();
		if (setExprBaseItemProvider != null) setExprBaseItemProvider.dispose();
		if (intExprItemProvider != null) intExprItemProvider.dispose();
		if (multExprItemProvider != null) multExprItemProvider.dispose();
		if (intBaseItemProvider != null) intBaseItemProvider.dispose();
		if (atomicItemProvider != null) atomicItemProvider.dispose();
		if (unspecifiedItemProvider != null) unspecifiedItemProvider.dispose();
		if (fragmentItemProvider != null) fragmentItemProvider.dispose();
		if (fragmentTypeItemProvider != null) fragmentTypeItemProvider.dispose();
		if (stateContextItemProvider != null) stateContextItemProvider.dispose();
		if (regionContextItemProvider != null) regionContextItemProvider.dispose();
		if (stateMachineContextItemProvider != null) stateMachineContextItemProvider.dispose();
		if (tranFragmentItemProvider != null) tranFragmentItemProvider.dispose();
		if (wcaFragmentListItemProvider != null) wcaFragmentListItemProvider.dispose();
		if (wcaFragmentItemProvider != null) wcaFragmentItemProvider.dispose();
		if (entityItemProvider != null) entityItemProvider.dispose();
		if (associationItemProvider != null) associationItemProvider.dispose();
		if (attributeItemProvider != null) attributeItemProvider.dispose();
		if (functionItemProvider != null) functionItemProvider.dispose();
		if (undefinedTypeItemProvider != null) undefinedTypeItemProvider.dispose();
		if (aggregationItemProvider != null) aggregationItemProvider.dispose();
		if (compositionItemProvider != null) compositionItemProvider.dispose();
		if (compDeclItemProvider != null) compDeclItemProvider.dispose();
		if (inputItemProvider != null) inputItemProvider.dispose();
		if (outputItemProvider != null) outputItemProvider.dispose();
		if (featureItemProvider != null) featureItemProvider.dispose();
		if (splItemProvider != null) splItemProvider.dispose();
		if (xorNodeItemProvider != null) xorNodeItemProvider.dispose();
		if (andNodeItemProvider != null) andNodeItemProvider.dispose();
		if (orNodeItemProvider != null) orNodeItemProvider.dispose();
		if (featureNodeItemProvider != null) featureNodeItemProvider.dispose();
		if (enumerationItemProvider != null) enumerationItemProvider.dispose();
		if (enumConstItemProvider != null) enumConstItemProvider.dispose();
		if (stateItemProvider != null) stateItemProvider.dispose();
		if (regionItemProvider != null) regionItemProvider.dispose();
		if (variableItemProvider != null) variableItemProvider.dispose();
	}

}
